version: '3'

services:
  database:
    image: 'mongo:5'
    restart: on-failure
    networks:
      - bosta-network
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-data:/bitnami'
    environment:
      # - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=api-monitor

  server:
    build:
      context: .
    restart: always
    networks:
      - bosta-network
    # volumes:
    # - /app/node_modules
    # - ./:/app/
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      PORT: 3000
      MONGO_URL: 'mongodb://database:27017/api-monitor'
      JWT_SECRET: JWT_SECRET

    # command: ['npm', 'run', 'dev']
    command: ['npm', 'start']

volumes:
  mongo-data:
    driver: local

networks:
  bosta-network:
